# Limpieza y Procesamiento de Datos de Incidencias (2026)

In [3]:
# Importar librerías principales de análisis y visualización
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Configuración estética de los gráficos
sns.set_theme(style="whitegrid", palette="muted")
plt.rcParams['figure.figsize'] = (12, 6)
plt.rcParams['font.sans-serif'] = ['DejaVu Sans', 'Arial', 'Helvetica']
plt.rcParams['axes.unicode_minus'] = False

# Evitar alertas innecesarias
import warnings
warnings.filterwarnings('ignore')

print("✅ Librerías cargadas exitosamente y entorno configurado.")

✅ Librerías cargadas exitosamente y entorno configurado.

# 📂 1. Importación y Carga de Datos

In [4]:
# Definir ruta del archivo original
file_path = "data/RNID-Delitos_Estatal-2026-abr2026.csv"

# Cargar el archivo con codificación latin1
try:
    df_raw = pd.read_csv(file_path, encoding='latin1')
    print(f"✅ Archivo cargado correctamente. Dimensiones del dataset original: {df_raw.shape[0]} filas y {df_raw.shape[1]} columnas.")
except Exception as e:
    print(f"❌ Error al cargar el archivo: {e}")

# Mostrar las primeras 5 filas del dataset original
df_raw.head()

✅ Archivo cargado correctamente. Dimensiones del dataset original: 3648 filas y 19 columnas.

,Año,Clave_Ent,Entidad,Bien jurídico afectado,Tipo de delito,Subtipo de delito,Modalidad,Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre
0,2026,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma blanca,1,1,1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2026,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma de fuego,4,3,2,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2026,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con otro elemento,0,0,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2026,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,No especificado,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2026,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Tentativa de homicidio doloso,Tentativa de homicidio doloso,1,0,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# 🔍 2. Diagnóstico de la Calidad de Datos

In [6]:
print("--- Información del Dataset ---")
df_raw.info()

# 2. Análisis de valores nulos
print("\n--- Valores Nulos por Columna ---")
nulls = df_raw.isnull().sum()
print(nulls[nulls>0] if nulls.sum() > 0 else "No se encontraron valores nulos.")

# 3. Análisis de valores duplicados
duplicates_count= df_raw.duplicated().sum()
print(f"\n --- Valores Duplicados--- \nCantidad de duplicados: {duplicates_count}")

# 4. Estadísticas para verificar anomarlías numéricas
print("\n --- Estadístiacs Descriptivas (Enero - Abril) ---")
df_raw[['Enero','Febrero', 'Marzo', 'Abril']].describe()

--- Información del Dataset ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3648 entries, 0 to 3647
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Año                     3648 non-null   int64
 1   Clave_Ent               3648 non-null   int64
 2   Entidad                 3648 non-null   object
 3   Bien jurídico afectado  3648 non-null   object
 4   Tipo de delito          3648 non-null   object
 5   Subtipo de delito       3648 non-null   object
 6   Modalidad               3648 non-null   object
 7   Enero                   3648 non-null   int64
 8   Febrero                 3648 non-null   int64
 9   Marzo                   3648 non-null   int64
 10  Abril                   3648 non-null   int64
 11  Mayo                    0 non-null      float64
 12  Junio                   0 non-null      float64
 13  Julio                   0 non-null      float64
 14  Agosto                  0 non-null      float64
 15  Septiembre              0 non-null      float64
 16  Octubre                 0 non-null      float64
 17  Noviembre               0 non-null      float64
 18  Diciembre               0 non-null      float64
dtypes: float64(8), int64(6), object(5)
memory usage: 541.6+ KB

--- Valores Nulos por Columna ---
Mayo          3648
Junio         3648
Julio         3648
Agosto        3648
Septiembre    3648
Octubre       3648
Noviembre     3648
Diciembre     3648
dtype: int64

 --- Valores Duplicados---
Cantidad de duplicados: 0

 --- Estadístiacs Descriptivas (Enero - Abril) ---

             Enero      Febrero        Marzo        Abril
count  3648.000000  3648.000000  3648.000000  3648.000000
mean     42.509046    41.278783    48.045504    46.988487
std     192.781886   174.861659   190.390442   203.210923
min       0.000000     0.000000     0.000000     0.000000
25%       0.000000     0.000000     0.000000     0.000000
50%       1.000000     1.000000     1.000000     1.000000
75%      20.000000    20.000000    24.000000    23.000000
max    7821.000000  6275.000000  5648.000000  7574.000000

# 📝 3. Estandarización de Nombres de Columnas y Texto

In [8]:
# Generar una copia del Dataset
df_clean = df_raw.copy()

# 1. Renombrar columnas con snake_case

columnas_renombradas = {
    'Año': 'anio',
    'Clave_Ent': 'clave_ent',
    'Entidad': 'entidad',
    'Bien jurídico afectado': 'bien_juridico_afectado',
    'Tipo de delito': 'tipo_delito',
    'Subtipo de delito': 'subtipo_delito',
    'Modalidad': 'modalidad',
    'Enero': 'enero',
    'Febrero': 'febrero',
    'Marzo': 'marzo',
    'Abril': 'abril',
    'Mayo': 'mayo',
    'Junio': 'junio',
    'Julio': 'julio',
    'Agosto': 'agosto',
    'Septiembre': 'septiembre',
    'Octubre': 'octubre',
    'Noviembre': 'noviembre',
    'Diciembre': 'diciembre'
}
df_clean.rename(columns=columnas_renombradas, inplace=True)

# 2. Formateo 'clave_ent' (2 digitos decimales)

df_clean['clave_ent'] = df_clean['clave_ent'].astype(str).str.zfill(2)

# 3. Limpiar espacios en blanco

columnas_texto = ['entidad', 'bien_juridico_afectado', 'tipo_delito', 'subtipo_delito', 'modalidad']
for col in columnas_texto:
    df_clean[col] = df_clean[col].astype(str).str.strip()

print("✅ Columnas renombradas y texto")
df_clean.head()

✅ Columnas renombradas y texto

,anio,clave_ent,entidad,bien_juridico_afectado,tipo_delito,subtipo_delito,modalidad,enero,febrero,marzo,abril,mayo,junio,julio,agosto,septiembre,octubre,noviembre,diciembre
0,2026,01,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma blanca,1,1,1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2026,01,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma de fuego,4,3,2,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2026,01,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con otro elemento,0,0,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2026,01,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,No especificado,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2026,01,Aguascalientes,La vida y la Integridad corporal,Homicidio,Tentativa de homicidio doloso,Tentativa de homicidio doloso,1,0,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# 🗑️ 4. Tratamiento de Columnas Vacías

In [9]:
meses_vacios = ['mayo', 'junio', 'julio', 'agosto', 'septiembre', 'octubre', 'noviembre', 'diciembre']

# Eliminar las columnas
df_clean.drop(columns=meses_vacios, inplace=True)

print(f"✅ Se eliminaron {len(meses_vacios)} columnas de meses futuros sin datos")
print(f"Nuevas dimensiones del Dataset: {df_clean.shape}")

df_clean.head()

✅ Se eliminaron 8 columnas de meses futuros sin datos
Nuevas dimensiones del Dataset: (3648, 11)

,anio,clave_ent,entidad,bien_juridico_afectado,tipo_delito,subtipo_delito,modalidad,enero,febrero,marzo,abril
0,2026,01,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma blanca,1,1,1,2
1,2026,01,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma de fuego,4,3,2,5
2,2026,01,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con otro elemento,0,0,1,1
3,2026,01,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,No especificado,0,0,0,0
4,2026,01,Aguascalientes,La vida y la Integridad corporal,Homicidio,Tentativa de homicidio doloso,Tentativa de homicidio doloso,1,0,1,0